import { Router } from 'express';
import admin from './routes/admin';
import advertisement from './routes/advertisement';
import auth from './routes/auth';
import campaign from './routes/campaign';
import commment from './routes/comment';
import dashboard from './routes/dashboard';
import event from './routes/event';
import feedback from './routes/feedback';
import login from './routes/login';
import logout from './routes/logout';
import notifications from './routes/notifications';
import post from './routes/post';
import reply from './routes/reply';
import user from './routes/user';

export default () => {
  const app = Router();
  auth(app);
  login(app);
  logout(app);
  user(app);
  post(app);
  feedback(app);
  commment(app);
  reply(app);
  notifications(app);
  admin(app);
  dashboard(app);
  event(app);
  campaign(app);
  advertisement(app);
  return app;
};
